# Generated by Django 5.0.6 on 2024-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_book_review_user_delete_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="pages",
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="quantity",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="details",
            field=models.TextField(default="No details available", max_length=1000),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.CharField(default="Not Available Data", max_length=40),
        ),
    ]
