# Generated by Django 5.0.6 on 2024-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_book_isbn_remove_book_pages_remove_book_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default="Philoshopy", max_length=100),
        ),
    ]
