# Generated by Django 5.0.6 on 2024-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recent_reads",
            field=models.ManyToManyField(
                related_name="readed_recent_by", to="app.book"
            ),
        ),
    ]
